sudo: required
dist: trusty
language:
  - java
jdk:
  - oraclejdk8  # Building Bazel requires JDK8.
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
      - sourceline: 'deb [arch=amd64] http://packages.cloud.google.com/apt cloud-sdk-trusty main'
        key_url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    packages:
      - bazel
      - google-cloud-sdk
      - kubectl


# TODO(mattmoor): Set up a cluster against which we will integration test PRs.
# before_install:
#   # Log into GCR
#   - docker login -u _json_key -p "${GOOGLE_JSON_KEY}" https://us.gcr.io
#   # Log into gcloud
#   - echo -n "${GOOGLE_JSON_KEY}" > keyfile.json
#   - gcloud auth activate-service-account --key-file keyfile.json
#   - rm -f keyfile.json
#   - gcloud config set core/project rules-k8s
#   - gcloud config set compute/zone us-central1-f
#   - gcloud container clusters get-credentials my-cluster-name

install:
  - go get -u github.com/bazelbuild/buildifier/buildifier

script:
  # Check that all of our tools and samples build
  - bazel clean && bazel build //...
  # Check that all of our tests pass
  - bazel clean && bazel test //...

  # Check for issues with the format of our bazel config files.
  - buildifier -mode=check $(find . -name BUILD -type f)
  - buildifier -mode=check $(find . -name WORKSPACE -type f)
  - buildifier -mode=check $(find . -name '*.bzl' -type f)

  # TODO(mattmoor): Run end-to-end testing against the cluster.
