apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-grpc-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-grpc-staging
    spec:
      containers:
      - name: hello-grpc
        image: us.gcr.io/rules_k8s/hello-grpc:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
